"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const mongoose_1 = __importDefault(require("mongoose"));
const talentScema = new mongoose_1.default.Schema({
    artist: { type: String, required: true },
    dateOfEvent: { type: Date, required: true },
    startTime: { type: String, required: true },
    talentArrivalTime: { type: String, required: true },
    eventName: { type: String, required: true },
    proposedOffer: { type: String, required: true },
    firstName: { type: String, required: true },
    lastName: { type: String, required: true },
    title: { type: String, required: true },
    email: { type: String, required: true },
    mobile: { type: String, required: true },
    companyName: { type: String, required: true },
    companyEmail: { type: String, required: true },
    officeAddress: { type: String, required: true },
    officeMobile: { type: String, required: true },
    signatoryFirstName: { type: String, required: true },
    sginatoryLastName: { type: String, required: true },
    signatoryTitle: { type: String, required: true },
    signatoryMobile: { type: String, required: true },
    venueNameAndAddress: { type: String, required: true },
    capacity: { type: String, required: true },
    venueClosestAirport: { type: String, required: true },
    eventType: { type: [String] },
    stageType: { type: [String] },
    announceDate: { type: Date, required: true },
    onSaleDate: { type: Date, required: true },
    loadInDate: { type: Date, required: true },
    loadInTime: { type: String, required: true },
    soundcheckTime: { type: String, required: true },
    doorsOpen: { type: String, required: true },
    eventStart: { type: String, required: true },
    setTimes: { type: String, required: true },
    setLength: { type: String, required: true },
    eventEnds: { type: String },
    curfew: { type: String },
    soundOrdinance: { type: String },
    purchaserProviders: { type: [String] },
    closestAirport: { type: String, required: true },
    techAdvance: { type: String, required: true },
    techAdvanceEmail: { type: String, required: true },
    techAdvancePhone: { type: String, required: true },
    expectationOfArtist: { type: String, required: true },
    mileageRestictions: { type: String, required: true },
    initialDeposit: { type: [String], required: true },
    guarantee: { type: String, required: true },
    advance: { type: String, required: true },
    numComps: { type: String, required: true },
    withholdingTax: { type: String, required: true },
    dateTimeTimezone: { type: String, required: true },
    commentsQuestions: { type: String, required: true },
    agreeTerms: { type: Boolean, required: true },
    signature: { type: String, required: true },
    signTitle: { type: String, required: true },
    signDate: { type: Date, required: true },
});
const Talent = mongoose_1.default.model("Talent", talentScema);
exports.default = Talent;
